### ISSUE TITLE
BillingResponse.BILLING_UNAVAILABLE errorCode: 3

### ISSUE THREAD

**Issue by HabeebCycle** [googlesamples/android-play-billing#103]
I implement iab in which I copied util folder and creating aidl in my app and uploaded it to playstore. I saw this library and implement it (play billing library) on the same app and I try to test it with the managed products on google play store but i am receiving an error code 3 (BILLING_UNAVAILABLE)
Please do I need to upload my app with the new library to app store in order to work? or am I making any error.
Thanks.

**Comment by vik17ag** [comment]
Even many of my users are getting the billing unavailable error message in spite of having the latest version of Google play app in their devices. 
**One user Example :** 
**play version** is : 8.8.13-all [0] [PR] 184707459
**Gradle library** : com.google.android.gms:play-services-auth:11.4.2
**Messge :**   RESULT_BILLING_UNAVAILABLE = 3 - This billing API version is not supported for the cellValue requested


I am using IInAppBillingService.aidl
[IInAppBillingService.aidl.txt](https://github.com/googlesamples/android-play-billing/files/1735873/IInAppBillingService.aidl.txt)

**Comment by cutler** [comment]
I had the same problem.


Version information:

> Samsung Note 8 Android 7.1.1
Play version is: 10.1.08-all [0] [PR] 196597404
compile 'com.android.billingclient:billing:1.0'

Is there a solution?

**Comment by HabeebCycle** [comment]
I implemented play billing library. It shows error code 3 (BILLING_UNAVAILABLE) when used with emulator. But works on a real device.

**Comment by cutler** [comment]
I downloaded and run TrivialDrive_v2 and replaced my package name with sku, but it still does not work on Samsung note8, but it works on other phones.

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the sample.

[Stackoverflow](https://stackoverflow.com/questions/tagged/in-app-billing) might be a better forum.

If you think that this is a problem in the Billings library, please open a bug on the Billing public issue tracker: https://issuetracker.google.com/issues/new?component=311487&template=1014446

Please reopen if you still think this is an issue with the sample.
