### ISSUE TITLE
getBuyIntentToReplaceSkus is not available in Google Play Billing Library r5

### ISSUE THREAD

**Issue by vovkab** [googlesamples/android-play-billing#3]
Version of Google Play Billing Library (r5) available through the android sdk manager doesn't have
`getBuyIntentToReplaceSkus`.

**Comment by RMarinaro** [comment]
I ran into the same issue but I was able to use the [.aidl in their project](https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive/app/src/main/aidl/com/android/vending/billing/IInAppBillingService.aidl), however

**Comment by defaultbr** [comment]
RMarianaro is correct, but i had this problem before, and the problem: i was doing the AIDL FOLDER inside the java class and not inside the src/main =x, after that, problem solved, check if you putting the .aidl in the correct place

**Comment by lomza** [comment]
In case somebody ran into this problem and wants to use _ITEM_TYPE_INAPP_ only (without subscriptions), you can safely remove `getBuyIntentToReplaceSkus()` calls and so no modifications will be required on _.aidl_ side.

You can take the modified working _IabHelper_ [code from here](https://github.com/lomza/IabHelper/blob/master/IabHelper.java).

**Comment by rpattabi** [comment]
Not sure why google is not maintaining this critical helper!

**Comment by zunware** [comment]
I fixed it by doing:

1. copy and paste the contents from the example's .aidl into my project's .aidl . 
2. Clean and build. 

Apparently Google's aidl is not the same from the example

**Comment by WhatFreshHellIsThis** [comment]
This is an extremely important sample and this critical issue is nearing a year old and is still not fixed.  What on earth is going on?   Even the docs are way outdated and I ran into similar issues with the Licensing LVL stuff before.  It's like it's been abandoned years ago or something.

**Comment by darko-v** [comment]
The sample is out of date. Library now uses  getBuyIntentExtraParams instead of getBuyIntentToReplaceSkus, according to current [documentation](https://developer.android.com/google/play/billing/billing_subscriptions.html). Problem is, that function is only available at release 6 and my Android studio only shows r5 available.
What a mess. 
getBuyIntentExtraParams is not present at r5, so it is not a documentation bug.

This method is only need for subscriptions, witch is my case. Anyone knows ho to get the r6? My Android Studio says that he is up to date.

**Comment by ravikumar-n** [comment]
The example present in `android-sdk/extras/google/play_billing/samples/TrivialDrive/` is up to date. Use that one, till this one is synced with new changes.

**Comment by EireiChen** [comment]
English documents is getBuyIntentExtraParams.
Other languages documents is getBuyIntentToReplaceSkus.

**Comment by Chieest** [comment]
Don't Google use google-translation??

**Comment by netomarin** [comment]
Hi all

The AIDL file is up-to-date.
Unfortunately we took too long to update last time, but now we are doing more recurrent checks.

Best regards
